# RADAR: The order makes a difference, and globbing Dir produces different results on different machines.
# We can .sort the glob, but still the order would be wrong, and we'd need to have repeated requires in
# Individual files. Michael and I think it's easier to statically call them all in one place in the right order.

__DIR__ = File.dirname(__FILE__)
require File.join(__DIR__, 'lib', 's_data')
require File.join(__DIR__, 'lib', 's_data', 'exceptions')
require File.join(__DIR__, 'lib', 's_data', 'formatting.rb')
require File.join(__DIR__, 'lib', 's_data', 'router_mixin.rb')
require File.join(__DIR__, 'lib', 's_data', 'sync', 'sdata_syncing_mixin.rb')
require File.join(__DIR__, 'lib', 's_data', 'sync', 'controller_mixin.rb')
require File.join(__DIR__, 'lib', 's_data', 'payload_map.rb')
require File.join(__DIR__, 'lib', 's_data', 'controller_mixin', 's_data_instance.rb')
require File.join(__DIR__, 'lib', 's_data', 'controller_mixin', 's_data_feed.rb')
require File.join(__DIR__, 'lib', 's_data', 'controller_mixin', 'collection_scope.rb')
require File.join(__DIR__, 'lib', 's_data', 'controller_mixin', 'actions.rb')
require File.join(__DIR__, 'lib', 's_data', 'atom_extensions', 'nodes', 'digest.rb')
require File.join(__DIR__, 'lib', 's_data', 'atom_extensions', 'nodes', 'payload.rb')
require File.join(__DIR__, 'lib', 's_data', 'atom_extensions', 'nodes', 'sync_state.rb')
require File.join(__DIR__, 'lib', 's_data', 'payload.rb')
require File.join(__DIR__, 'lib', 's_data', 'route_mapper.rb')
require File.join(__DIR__, 'lib', 's_data', 'atom_extensions', 'content_mixin.rb')
require File.join(__DIR__, 'lib', 's_data', 'atom_extensions', 'entry_mixin.rb')
require File.join(__DIR__, 'lib', 's_data', 'namespace_definitions.rb')
require File.join(__DIR__, 'lib', 's_data', 'predicate.rb')
require File.join(__DIR__, 'lib', 's_data', 'active_record_extensions', 'mixin.rb')
require File.join(__DIR__, 'lib', 's_data', 'active_record_extensions', 'sdata_uuid_mixin.rb')
require File.join(__DIR__, 'lib', 's_data', 'active_record_extensions', 'base.rb')
require File.join(__DIR__, 'lib', 's_data', 'virtual_base.rb')
require File.join(__DIR__, 'lib', 's_data', 'conditions_builder.rb')
require File.join(__DIR__, 'lib', 's_data', 'controller_mixin.rb')
require File.join(__DIR__, 'lib', 's_data', 'payload_map', 'payload_map_hash.rb')
require File.join(__DIR__, 'lib', 's_data', 'payload_map', 'payload_map.rb')
require File.join(__DIR__, 'lib', 's_data', 'diagnosis', 'diagnosis.rb')
require File.join(__DIR__, 'lib', 's_data', 'diagnosis', 'application_controller_mixin.rb')
require File.join(__DIR__, 'lib', 's_data', 'diagnosis', 'diagnosis_mapper.rb')